<li><a href="index.php">Home</a></li>
<li><a href="why_us.php">Why Us</a></li>
<li><a href="getting_started.php">Getting Started</a></li>
<li><a href="package_types.php">Package Types</a></li>
<li><a href="profit_history.php">Profit History</a></li>
<li><a href="faq.php">FAQ</a></li>
<li><a href="testimonials.php">Testimonials</a></li>
<li><a href="news_room.php">Newsroom</a></li>
<li><a href="contacts.php">Contacts</a></li>